{
  ##################
  #-=# SECURITY #=-#
  ##################
  security = {
    pki = {
      certificates = [
        ''
          -----BEGIN CERTIFICATE-----
          MIIB2TCCAX6gAwIBAgIQDSDy/7kGfWlSLhRO0lniZzAKBggqhkjOPQQDAjA2MRUw
          EwYDVQQKEwxhZG0ucGtpLmNvcnAxHTAbBgNVBAMTFGFkbS5wa2kuY29ycCBSb290
          IENBMB4XDTI1MDgxODA3MzkyN1oXDTM1MDgxNjA3MzkyN1owPjEVMBMGA1UEChMM
          YWRtLnBraS5jb3JwMSUwIwYDVQQDExxhZG0ucGtpLmNvcnAgSW50ZXJtZWRpYXRl
          IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEj0NnvgVcf3Bh24SGSRNlbcHz
          obQ41rfA82eAIYwNLLUQaCFzNPZXYOgX5W1n11gxML5m8DriPm4CnW6FRTuWFqNm
          MGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYE
          FIh2qKtttQJ6PwNnulUypLs0kxp7MB8GA1UdIwQYMBaAFMClmcWUvuYuIXAQgm4D
          OtduJnySMAoGCCqGSM49BAMCA0kAMEYCIQCVyqYsrSMBNt1xvygdpnWmu/yJoguN
          s0bl8qtqU6eXmwIhAPaba5Dm1XYqU4ReUJ/SxzDymrvz5s/vHQbKBy8nE9gu
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIBrjCCAVWgAwIBAgIQMwjUkUNULRBCJsMruMeHxTAKBggqhkjOPQQDAjA2MRUw
          EwYDVQQKEwxhZG0ucGtpLmNvcnAxHTAbBgNVBAMTFGFkbS5wa2kuY29ycCBSb290
          IENBMB4XDTI1MDgxODA3MzkyNloXDTM1MDgxNjA3MzkyNlowNjEVMBMGA1UEChMM
          YWRtLnBraS5jb3JwMR0wGwYDVQQDExRhZG0ucGtpLmNvcnAgUm9vdCBDQTBZMBMG
          ByqGSM49AgEGCCqGSM49AwEHA0IABIUPzCSwMKlyZvetni6+9JuKkEALawHqrYUF
          7ROXhwf3I2IeG9oinPgNVy1pHs0PAOESqLX2iliDWs9oly0X6iqjRTBDMA4GA1Ud
          DwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBTApZnFlL7m
          LiFwEIJuAzrXbiZ8kjAKBggqhkjOPQQDAgNHADBEAiAHLAqk5H0fRmVypx1HGTJG
          mnXrjbvDc3ao8GmxK84ncAIgK2hD8rokSz3IohySOzMRg5Tj8qVC12mEH1/lT7bi
          uSE=
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIDKTCCAs+gAwIBAgIBADAKBggqhkjOPQQDAjCBzDELMAkGA1UEBhMCREUxGzAZ
          BgNVBAgMElNDSExFU1dJRyBIT0xTVEVJTjEWMBQGA1UEBwwNQkFEIFNDSFdBUlRB
          VTEYMBYGA1UECgwPREVCSVRPUiBJTktBU1NPMRswGQYDVQQLDBJERUJJVE9SIElO
          S0FTU08gSVQxHDAaBgkqhkiG9w0BCQEWDUlUQERFQklUT1IuREUxMzAxBgNVBAMM
          KkRFQklUT1IgSU5LQVNTTyBJVCBJTlRFUk5BTCBJTkZSQVNUUlVDVFVSRTAgFw0y
          NTA4MTMwNjE2NDJaGA8yMTQwMDgxMDA2MTY0MlowgcwxCzAJBgNVBAYTAkRFMRsw
          GQYDVQQIDBJTQ0hMRVNXSUcgSE9MU1RFSU4xFjAUBgNVBAcMDUJBRCBTQ0hXQVJU
          QVUxGDAWBgNVBAoMD0RFQklUT1IgSU5LQVNTTzEbMBkGA1UECwwSREVCSVRPUiBJ
          TktBU1NPIElUMRwwGgYJKoZIhvcNAQkBFg1JVEBERUJJVE9SLkRFMTMwMQYDVQQD
          DCpERUJJVE9SIElOS0FTU08gSVQgSU5URVJOQUwgSU5GUkFTVFJVQ1RVUkUwWTAT
          BgcqhkjOPQIBBggqhkjOPQMBBwNCAARFBsicWu/D5hSgDB1mO5DrMVgseGwVvenr
          cplrBuSPqIPyTSaLZkTmpUYl6HlWrFDXz8m6fctJdiskloYpyap8o4GdMIGaMDcG
          CWCGSAGG+EIBDQQqFihPUE5zZW5zZSBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUgQXV0
          aG9yaXR5MB0GA1UdDgQWBBTWavfMDBZ1xNMbivZdKtxxiRPoATAfBgNVHSMEGDAW
          gBTWavfMDBZ1xNMbivZdKtxxiRPoATAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB
          /wQEAwIBhjAKBggqhkjOPQQDAgNIADBFAiAxyw5w3nf0bPvBgQX6O5g+bZDeWTET
          TAdM2AmT60+E8wIhAP+6+IWnBh+J/1cJKbIVaDsqSfFfZVMs0Ucj8EWABNyD
          -----END CERTIFICATE-----
        ''
      ];
    };
  };
}
