{
  ##################
  #-=# SECURITY #=-#
  ##################
  security = {
    pki = {
      certificates = [
        ''
          -----BEGIN CERTIFICATE-----
          MIIBmjCCAUGgAwIBAgIQeLqiGJEfATE/LpKT96khmTAKBggqhkjOPQQDAjAsMRAw
          DgYDVQQKEwdob21lbGFiMRgwFgYDVQQDEw9ob21lbGFiIFJvb3QgQ0EwHhcNMjUx
          MDI2MTQzMTM1WhcNMzUxMDI0MTQzMTM1WjAsMRAwDgYDVQQKEwdob21lbGFiMRgw
          FgYDVQQDEw9ob21lbGFiIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
          AAT8NzCaCOOl+prX8pXGZp1aXDlSjz5RH31abVHSGgekUuqmnWnF6wrDKvMPWDs+
          eunAe2ZJ3aoQB1Xr15AdY6Mgo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/
          BAgwBgEB/wIBATAdBgNVHQ4EFgQUVN0IqQWKArSXQdFVfQaNTv0bZg8wCgYIKoZI
          zj0EAwIDRwAwRAIge0ClrJ/YZJLxecEKjp809KtTlUDymQyXZ8TYP4wPm9ECIBkd
          L/owkMWcN/LnN3FrW0iwkgQpl4yADI2+vKa2dL2o
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIBxTCCAWugAwIBAgIRAKxVlg78eCf58Ba3r73FGlEwCgYIKoZIzj0EAwIwLDEQ
          MA4GA1UEChMHaG9tZWxhYjEYMBYGA1UEAxMPaG9tZWxhYiBSb290IENBMB4XDTI1
          MTAyNjE0MzEzNloXDTM1MTAyNDE0MzEzNlowNDEQMA4GA1UEChMHaG9tZWxhYjEg
          MB4GA1UEAxMXaG9tZWxhYiBJbnRlcm1lZGlhdGUgQ0EwWTATBgcqhkjOPQIBBggq
          hkjOPQMBBwNCAASVJBygcOAfZiTaZTseRHL08PAXiMOQUA7paFtaPPSTe1dxtrfx
          eE1RWXGyDGP/K/bk40nn8Bt1WzOxNaD0863zo2YwZDAOBgNVHQ8BAf8EBAMCAQYw
          EgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUDlq5Y5iQjxhIr5ss76WQf5U9
          EkYwHwYDVR0jBBgwFoAUVN0IqQWKArSXQdFVfQaNTv0bZg8wCgYIKoZIzj0EAwID
          SAAwRQIhAN+hzks0Z09eZK/YWztpdkJSSVRPdtgGKQ7C8uan3pOLAiBqO3gyD4ed
          ZkeKuMa4+VYkM9XkV9vdfBupx6HHCBRXqg==
          -----END CERTIFICATE-----
        ''
      ];
    };
  };
  #####################
  #-=# ENVIRONMENT #=-#
  #####################
  environment = {
    etc."rootCA.crt".text = ''
      -----BEGIN CERTIFICATE-----
      MIIBmjCCAUGgAwIBAgIQeLqiGJEfATE/LpKT96khmTAKBggqhkjOPQQDAjAsMRAw
      DgYDVQQKEwdob21lbGFiMRgwFgYDVQQDEw9ob21lbGFiIFJvb3QgQ0EwHhcNMjUx
      MDI2MTQzMTM1WhcNMzUxMDI0MTQzMTM1WjAsMRAwDgYDVQQKEwdob21lbGFiMRgw
      FgYDVQQDEw9ob21lbGFiIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
      AAT8NzCaCOOl+prX8pXGZp1aXDlSjz5RH31abVHSGgekUuqmnWnF6wrDKvMPWDs+
      eunAe2ZJ3aoQB1Xr15AdY6Mgo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/
      BAgwBgEB/wIBATAdBgNVHQ4EFgQUVN0IqQWKArSXQdFVfQaNTv0bZg8wCgYIKoZI
      zj0EAwIDRwAwRAIge0ClrJ/YZJLxecEKjp809KtTlUDymQyXZ8TYP4wPm9ECIBkd
      L/owkMWcN/LnN3FrW0iwkgQpl4yADI2+vKa2dL2o
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIBxTCCAWugAwIBAgIRAKxVlg78eCf58Ba3r73FGlEwCgYIKoZIzj0EAwIwLDEQ
      MA4GA1UEChMHaG9tZWxhYjEYMBYGA1UEAxMPaG9tZWxhYiBSb290IENBMB4XDTI1
      MTAyNjE0MzEzNloXDTM1MTAyNDE0MzEzNlowNDEQMA4GA1UEChMHaG9tZWxhYjEg
      MB4GA1UEAxMXaG9tZWxhYiBJbnRlcm1lZGlhdGUgQ0EwWTATBgcqhkjOPQIBBggq
      hkjOPQMBBwNCAASVJBygcOAfZiTaZTseRHL08PAXiMOQUA7paFtaPPSTe1dxtrfx
      eE1RWXGyDGP/K/bk40nn8Bt1WzOxNaD0863zo2YwZDAOBgNVHQ8BAf8EBAMCAQYw
      EgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUDlq5Y5iQjxhIr5ss76WQf5U9
      EkYwHwYDVR0jBBgwFoAUVN0IqQWKArSXQdFVfQaNTv0bZg8wCgYIKoZIzj0EAwID
      SAAwRQIhAN+hzks0Z09eZK/YWztpdkJSSVRPdtgGKQ7C8uan3pOLAiBqO3gyD4ed
      ZkeKuMa4+VYkM9XkV9vdfBupx6HHCBRXqg==
      -----END CERTIFICATE-----
    '';
  };
}
