{
  ##################
  #-=# SECURITY #=-#
  ##################
  security = {
    pki = {
      certificates = [
        ''
          pki.adm.corp 2025-06-22
          =========
          -----BEGIN CERTIFICATE-----
          MIIBmDCCAT6gAwIBAgIRANCOBc5UkeoNFyhYVF98RyswCgYIKoZIzj0EAwIwKjEP
          MA0GA1UEChMGY29ycENBMRcwFQYDVQQDEw5jb3JwQ0EgUm9vdCBDQTAeFw0yNTA2
          MjIxMTMwNDVaFw0zNTA2MjAxMTMwNDVaMCoxDzANBgNVBAoTBmNvcnBDQTEXMBUG
          A1UEAxMOY29ycENBIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASf
          12cHlLHHifIpy7TtbfFf6NlAb91jX9SrTAVY5giL6AUGoMmXoPs+TkALeVdi6xUu
          Fm1usLMOa75X12HYZgVoo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgw
          BgEB/wIBATAdBgNVHQ4EFgQUaf1jOF16aqqiOeHToshVbMFGUGgwCgYIKoZIzj0E
          AwIDSAAwRQIgREbg5gpwLHXxcvhEJTYI1Ctoop4sLCjtZvcbaPKhjncCIQCsahtW
          xTKaGhOwOrx8HinlIMGTnICKj+Jn/aJETzam/A==
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIBwDCCAWagAwIBAgIQc7zIS1tougigI2pni9VghjAKBggqhkjOPQQDAjAqMQ8w
          DQYDVQQKEwZjb3JwQ0ExFzAVBgNVBAMTDmNvcnBDQSBSb290IENBMB4XDTI1MDYy
          MjExMzA0NloXDTM1MDYyMDExMzA0NlowMjEPMA0GA1UEChMGY29ycENBMR8wHQYD
          VQQDExZjb3JwQ0EgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAEQR9HICjgGUjt/Zg22aD3yq9lscNvelw6eUGoQKuEXDFRo/lws3xDVl4F
          FDbiLFgCN++Aoe8LAY1x/mxVTTag6KNmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1Ud
          EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFAZc2IxK8YPWh2Ikdd6QoGDUBZ6PMB8G
          A1UdIwQYMBaAFGn9Yzhdemqqojnh06LIVWzBRlBoMAoGCCqGSM49BAMCA0gAMEUC
          IQD8GgVr6Dntgg79epMEcQ4wxTgs3SA0UPjKsatDWrEqfgIgFrr/4aSRTdBdUlE5
          6x4dgGXFXdppeqFfJ1fyTw4QYVQ=
          -----END CERTIFICATE-----
        ''
      ];
    };
  };
  #####################
  #-=# ENVIRONMENT #=-#
  #####################
  environment = {
    etc."ca.crt".text = ''
      -----BEGIN CERTIFICATE-----
      MIIBmDCCAT6gAwIBAgIRANCOBc5UkeoNFyhYVF98RyswCgYIKoZIzj0EAwIwKjEP
      MA0GA1UEChMGY29ycENBMRcwFQYDVQQDEw5jb3JwQ0EgUm9vdCBDQTAeFw0yNTA2
      MjIxMTMwNDVaFw0zNTA2MjAxMTMwNDVaMCoxDzANBgNVBAoTBmNvcnBDQTEXMBUG
      A1UEAxMOY29ycENBIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASf
      12cHlLHHifIpy7TtbfFf6NlAb91jX9SrTAVY5giL6AUGoMmXoPs+TkALeVdi6xUu
      Fm1usLMOa75X12HYZgVoo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgw
      BgEB/wIBATAdBgNVHQ4EFgQUaf1jOF16aqqiOeHToshVbMFGUGgwCgYIKoZIzj0E
      AwIDSAAwRQIgREbg5gpwLHXxcvhEJTYI1Ctoop4sLCjtZvcbaPKhjncCIQCsahtW
      xTKaGhOwOrx8HinlIMGTnICKj+Jn/aJETzam/A==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIBwDCCAWagAwIBAgIQc7zIS1tougigI2pni9VghjAKBggqhkjOPQQDAjAqMQ8w
      DQYDVQQKEwZjb3JwQ0ExFzAVBgNVBAMTDmNvcnBDQSBSb290IENBMB4XDTI1MDYy
      MjExMzA0NloXDTM1MDYyMDExMzA0NlowMjEPMA0GA1UEChMGY29ycENBMR8wHQYD
      VQQDExZjb3JwQ0EgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0D
      AQcDQgAEQR9HICjgGUjt/Zg22aD3yq9lscNvelw6eUGoQKuEXDFRo/lws3xDVl4F
      FDbiLFgCN++Aoe8LAY1x/mxVTTag6KNmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1Ud
      EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFAZc2IxK8YPWh2Ikdd6QoGDUBZ6PMB8G
      A1UdIwQYMBaAFGn9Yzhdemqqojnh06LIVWzBRlBoMAoGCCqGSM49BAMCA0gAMEUC
      IQD8GgVr6Dntgg79epMEcQ4wxTgs3SA0UPjKsatDWrEqfgIgFrr/4aSRTdBdUlE5
      6x4dgGXFXdppeqFfJ1fyTw4QYVQ=
      -----END CERTIFICATE-----
    '';
  };
}
