{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."timetrack" = {
    image = "openducks/timetrack:latest";
    volumes = [
      "/tmp/timetrack:/var/www/html:rw"
    ];
    ports = [
      "8080:80/tcp"
    ];
    dependsOn = [
      "timetrack-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=timetrack"
      "--network=timetrack_default"
    ];
  };
  systemd.services."podman-timetrack" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-timetrack_default.service"
    ];
    requires = [
      "podman-network-timetrack_default.service"
    ];
    partOf = [
      "podman-compose-timetrack-root.target"
    ];
    wantedBy = [
      "podman-compose-timetrack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."timetrack-db" = {
    image = "mariadb:11";
    environment = {
      "MYSQL_DATABASE" = "ab";
      "MYSQL_PASSWORD" = "yourpassword";
      "MYSQL_ROOT_PASSWORD" = "root";
      "MYSQL_USER" = "timetool";
    };
    volumes = [
      "timetrack_db_data:/var/lib/mysql:rw"
    ];
    cmd = ["--character-set-server=utf8mb4" "--collation-server=utf8mb4_unicode_ci"];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=timetrack_default"
    ];
  };
  systemd.services."podman-timetrack-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-timetrack_default.service"
      "podman-volume-timetrack_db_data.service"
    ];
    requires = [
      "podman-network-timetrack_default.service"
      "podman-volume-timetrack_db_data.service"
    ];
    partOf = [
      "podman-compose-timetrack-root.target"
    ];
    wantedBy = [
      "podman-compose-timetrack-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-timetrack_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f timetrack_default";
    };
    script = ''
      podman network inspect timetrack_default || podman network create timetrack_default
    '';
    partOf = ["podman-compose-timetrack-root.target"];
    wantedBy = ["podman-compose-timetrack-root.target"];
  };

  # Volumes
  systemd.services."podman-volume-timetrack_db_data" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect timetrack_db_data || podman volume create timetrack_db_data
    '';
    partOf = ["podman-compose-timetrack-root.target"];
    wantedBy = ["podman-compose-timetrack-root.target"];
  };

  systemd.targets."podman-compose-timetrack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
