# PREP
BRAND?=debiguard
NETWORK?=10.20.66
TARGETDIR?=~/Downloads

###########
# GENERIC #
###########
all:
	@echo "ID=111" make gen

gen:
	@echo "Write openwrt restore file and wg.config into $(TARGETDIR)"
	sh ./genall.sh
