#!/usr/bin/make
# add pkgs.gnumake to your nix base config!
.ONESHELL:

#################################
# PERSONAL ADMIN SPECIFIC SETUP #
#################################
ADMIN_OPN_USER?=admin-mpaepcke
ADMIN_SSH_SMARTCARD?=~/.ssh/id_ed25519_sk
MYIP=250

###############################
# WIREGUARD YUBIKEY KEY-STORE #
###############################
# needs: pkgs.yubikey-manager (setup and runtime)
# needs: pkgs.wg-wireguard-tools (runtime)
# YUBIKEY_SERIAL: 	make yubikey.info
# WG_IV: 		make rekey.iv

YUBIKEY_SERIAL=12399123 # example
WG_IV=e7bf023cf77ba4bc38829765ca76eecc1 # example

include /etc/nixos/admin/Makefile.Site.Home
include /etc/nixos/admin/Makefile.Generic
