#!/usr/bin/make
# add pkgs.gnumake to your nix base config!
.ONESHELL:

#################################
# PERSONAL ADMIN SPECIFIC SETUP #
#################################
OPN_ADMIN_ID?=admin-mpaepcke
ADMIN_SSH_SMARTCARD?=~/.ssh/id_ed25519_sk_admin

include /etc/nixos/admin/Makefile.Site.Home
include /etc/nixos/admin/Makefile.Generic
